Licenta/Licenta/Controllers/SupprliersController.cs
using System.Web.Mvc;
using DatabaseModel;
using System.Net;
using Licenta.Models;
using System.Collections.Generic;

namespace Licenta.Controllers
{
    [Authorize]
    public class SuppliersController : Controller
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (SessionAccessor.LoggedUser == null)
            {
                filterContext.Result = RedirectToAction("Login", "Home");
                return;
            }

            if ((int)Session["role"] < 3)
            {
                filterContext.Result = RedirectToAction("Home", "Home");
                return;
            }
        }

        // GET: Suppliers
        public ActionResult Index()
        {
            var suppliers = SupplierContainer.GetSuppliers();

            return View(suppliers);
        }

        // GET: Deliveries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Deliveries/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                SupplierContainer.SaveSupplier(supplier);
                return RedirectToAction("Index");
            }
            var model = new SupplierModel();
            model.Supplier = supplier;

            return View(model);
        }

        // POST: Deliveries/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                SupplierContainer.SaveSupplier(supplier);
                return RedirectToAction("Index");
            }

            return View(supplier);
        }


        // GET: Deliveries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var model = new SupplierModel();
            model.Supplier = SupplierContainer.getSupplierById((int) id);

            return View(model);
        }

        // GET: Deliveries/Delete/5
        public ActionResult Delete(int id)
        {
            if (id < 1)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            SupplierContainer.DeleteSupplier(id);

            return RedirectToAction("Index");
        }
    }
}

Licenta/Licenta/Views/Suppliers/Create.cshtml
@model Licenta.Models.SupplierModel
@{
    ViewBag.Title = "Furnizori";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
@Scripts.Render("~/bundles/Logged")

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="container pagination-centered">
        <div class="containerWrapper col-md-8 col-md-offset-2">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <h3>Furnizor nou:</h3>
                <br />
                <div class="form-group">
                   <div class="form-group">
                        <strong class="control-label col-md-3 ">Nume:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Supplier.Nume, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Supplier.Nume, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Adresa:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Supplier.Adresa, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Supplier.Adresa, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Oras:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Supplier.Oras, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Supplier.Oras, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Telefon:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Supplier.Telefon, new { htmlAttributes = new { @class = "form-control", @rows = 8, @type="number" } })
                            @Html.ValidationMessageFor(model => Model.Supplier.Telefon, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 ">
                        <input type="submit" value="Creaza" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Licenta/Licenta/Views/Suppliers/Edit.cshtml
@model  Licenta.Models.SupplierModel
@{
    ViewBag.Title = "Furnizari";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
@Scripts.Render("~/bundles/Logged")

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <div class="container pagination-centered">
        <div class="containerWrapper col-md-8 col-md-offset-2">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Supplier.ID)
                <br />
                <div class="form-group">
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Nume:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Supplier.Nume, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Supplier.Nume, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Adresa:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Supplier.Adresa, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Supplier.Adresa, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Oras:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Supplier.Oras, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Supplier.Oras, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Telefon:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Supplier.Telefon, new { htmlAttributes = new { @class = "form-control", @rows = 8, @type="number"} })
                            @Html.ValidationMessageFor(model => Model.Supplier.Telefon, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 ">
                        <input type="submit" value="Modifica" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Licenta/Licenta/Views/Suppliers/Index.cshtml
@{
    ViewBag.Title = "Furnizari";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.1.1/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.1.1/js/responsive.bootstrap.min.js"></script>
<script>
    $(document).ready(function () {
        $('#datatable').dataTable({
            "columnDefs": [{
                "targets": 'no-sort',
                "orderable": false,
            }]
        });
    });
</script>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css">
@Scripts.Render("~/bundles/Logged")

<div class="container pagination-centered">
    <div class="col-md-12">
        <div class="dataTables_wrapper form-inline dt-bootstrap containerWrapper">
            <div class="table-responsive">
                <table id="datatable" class="table dataTable">
                    <thead>
                        <tr>
                            <th id="id"></th>
                            <th>Nume</th>
                            <th>Adresa</th>
                            <th>Oras</th>
                            <th>Telefon</th>
                            <th class="col-xs-1 no-sort">
                                <button id="add" onclick="location.href='@Url.Action("Create", "Suppliers")'" />
                            </th>
                        </tr>
                    </thead>
                    <tbody id="table">
                        @foreach (var item in Model)
                        {
                            <tr class="addedrow">
                                <td id="id">@item.ID</td>
                                <td id="nume">@item.Nume</td>
                                <td>@item.Adresa</td>
                                <td>@item.Oras</td>
                                <td>@item.Telefon</td>
                                <td>
                                    <button class="edit" onclick="location.href='@Url.Action("Edit", "Suppliers", new { id = item.ID})'"></button>
                                    <button class="delete"></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>