Licenta/Licenta/Controllers/MarketsController.cs
using System.Web.Mvc;
using DatabaseModel;
using System.Net;
using Licenta.Models;
using System.Web;
using System.IO;

namespace Licenta.Controllers
{
    [Authorize]
    public class MarketsController : Controller
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (SessionAccessor.LoggedUser == null)
            {
                filterContext.Result = RedirectToAction("Login", "Home");
                return;
            }

            if ((int)Session["role"] < 3)
            {
                filterContext.Result = RedirectToAction("Home", "Home");
                return;
            }
        }

        // GET: Suppliers
        public ActionResult Index()
        {
            var markets = MarketContainer.GetMarkets();

            return View(markets);
        }

        // GET: Deliveries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Deliveries/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase postedFile, Market market)
        {
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    var filename = "img_" + market.Denumire.ToLower() + ".png";
                    var path = Path.Combine(Server.MapPath("~/Content/ProductsImages/"), filename);
                    postedFile.SaveAs(path);
                    market.Imagine = "img_" + market.Denumire.ToLower();
                }

                MarketContainer.SaveMarket(market);
                return RedirectToAction("Index");
            }
            var model = new MarketModel();
            model.Market = market;

            return View(model);
        }

        // POST: Deliveries/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase postedFile, Market market)
        {
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    var filename = "img_" + market.Denumire.ToLower() + ".png";
                    var path = Path.Combine(Server.MapPath("~/Content/ProductsImages/"), filename);
                    postedFile.SaveAs(path);
                    market.Imagine = "img_" + market.Denumire.ToLower();
                }

                MarketContainer.SaveMarket(market);
                return RedirectToAction("Index");
            }

            return View(market);
        }


        // GET: Deliveries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var model = new MarketModel();
            model.Market = MarketContainer.getMarketById((int) id);

            return View(model);
        }

        // GET: Deliveries/Delete/5
        public ActionResult Delete(int id)
        {
            if (id < 1)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            string serverpath = Server.MapPath("~/Content/ProductsImages/");
            MarketContainer.DeleteMatket(id, serverpath);

            return RedirectToAction("Index");
        }
    }
}

Licenta/Licenta/Views/Markets/Create.cshtml
@model Licenta.Models.MarketModel
@{
    ViewBag.Title = "Magazine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
@Scripts.Render("~/bundles/Logged")

@using (Html.BeginForm("Create", "Markets", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    <div class="container pagination-centered">
        <div class="containerWrapper col-md-8 col-md-offset-2">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <h3>Magazin nou:</h3>
                <br />
                <div class="form-group">
                   <div class="form-group">
                        <strong class="control-label col-md-3 ">Adresa:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Market.Adresa, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Market.Adresa, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Denumire:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Market.Denumire, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Market.Denumire, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Oras:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Market.Oras, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Market.Oras, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Imagine:</strong>
                        <div class="col-md-8">
                            <input type="file" name="postedFile" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 ">
                        <input type="submit" value="Creaza" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Licenta/Licenta/Views/Markets/Edit.cshtml
@model  Licenta.Models.MarketModel
@{
    ViewBag.Title = "Magazine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
@Scripts.Render("~/bundles/Logged")

@using (Html.BeginForm("Edit", "Markets", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    <div class="container pagination-centered">
        <div class="containerWrapper col-md-8 col-md-offset-2">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Market.ID)
                <br />
                <div class="form-group">
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Adresa:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Market.Adresa, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Market.Adresa, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Denumire:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Market.Denumire, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Market.Denumire, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Oras:</strong>
                        <div class="col-md-8">
                            @Html.EditorFor(model => Model.Market.Oras, new { htmlAttributes = new { @class = "form-control", @rows = 8 } })
                            @Html.ValidationMessageFor(model => Model.Market.Oras, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <strong class="control-label col-md-3 ">Imagine:</strong>
                        <div class="col-md-8">
                            <input type="file" name="postedFile" />
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10 ">
                        <input type="submit" value="Modifica" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Licenta/Licenta/Views/Markets/Index.cshtml
@{
    ViewBag.Title = "Magazine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.1.1/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.1.1/js/responsive.bootstrap.min.js"></script>
<script>
    $(document).ready(function (){
        $('#datatable').dataTable( {
            "columnDefs": [ {
                "targets": 'no-sort',
                "orderable": false,
            } ]
        } );
    });
</script>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css">
@Scripts.Render("~/bundles/Logged")

<div class="container pagination-centered">
    <div class="col-md-12">
        <div class="dataTables_wrapper form-inline dt-bootstrap containerWrapper">
            <div class="table-responsive">
                <table id="datatable" class="table dataTable">
                    <thead>
                        <tr>
                            <th id="id"></th>
                            <th>Adresa</th>
                            <th>Denumire</th>
                            <th>Oras</th>
                            <th>Imagine</th>
                            <th class="col-xs-1 no-sort">
                                <button id="add" onclick="location.href='@Url.Action("Create", "Markets")'" />
                            </th>
                        </tr>
                    </thead>
                    <tbody id="table">
                        @foreach (var item in Model)
                        {
                            <tr class="addedrow">
                                <td id="id">@item.ID</td>
                                <td>@item.Adresa</td>
                                <td id="nume">@item.Denumire</td>
                                <td>@item.Oras</td>
                                <td><img class="img" src="~/Content/ProductsImages/@(item.Imagine).png" /></td>
                                <td>
                                    <button class="edit" onclick="location.href='@Url.Action("Edit", "Markets", new { id = item.ID})'"></button>
                                    <button class="delete"></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>